### ISSUE TITLE
Why is game mode not working?

### ISSUE THREAD

**Issue by Tsury** [MasterMann/Dota2-DiscordRP#1]
Is it because GSI does not supply it?

**Comment by MasterMann** [comment]
Game Mode is available via server.log file. I'm planning to update the project and add that functionality later.

**Comment by Tsury** [comment]
Well, notice that server_log.txt does not really give you all the info you need when it comes to game modes. For instance, both Unranked All Pick and Ranked All Pick both use DOTA_GAMEMODE_ALL_DRAFT.

**Comment by MasterMann** [comment]
Unfortunately I don't have any other way to get the game mode info. If you know any - feel free to tell
